# Generated by Django 4.1.4 on 2022-12-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_session_stats_session_year_session_starts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_year',
            old_name='session_starts',
            new_name='session_start',
        ),
    ]
